### ISSUE TITLE
Calculated Rao Q in hillR and FD packages are different

### ISSUE THREAD

**Issue by BErfanian** [daijiang/hillR#3]
Hi,
I test your code and the trial data "dummy", comparing the results of FD package and hillR, The reported Rao Q are different, because of dependencies of hill functional diversity numbers on RaoQ, I think the calculated Functional hill numbers in your code are not correct.
Regards,
Bagher

**Comment by daijiang** [comment]
The differences between results from FD and here is because of different formulas used in calculating RaoQ.

FD uses `ade4::divc()` to calculate Rao's Q, which is [(here for source code lines 564-565):](https://github.com/cran/FD/blob/master/R/dbFD.R)

         `div[i, ] <- (t(df[, i]) %*% (as.matrix(dis)^2) %*% df[, i])/2/(sum(df[, i])^2)`

See that instead of use formula $\sum \sum p_{i} d_{ij} p_{j}$, they used d_ij ^2 and then divided results with 2 and then (sum(df[, i])^2).

Instead, in my code, i just used the original formula $\sum \sum p_{i} d_{ij} p_{j}$, c.f. Chiu and Chao 2013 Plos One.

If you change the FD code, (lines 564-565 in the above url) to `div[i, ] <- (t(df[, i]) %*% (as.matrix(dis)^1) %*% df[, i])`, we get the same results.

Another possible result for differences between results from FD and here is the many many pre-calculation data manipulations. 

Thanks for your comment.

**Comment by BErfanian** [comment]
I've checked both of codes, and I noticed it before, Chiu and Chao 2013 fermula for Q is as the Botta-Dukát 2005 (FD refers to this article for Rao's Q formula). 
I don't know why FD use ^2 and /2.
Thanks. 
p.s: It will be great if you implement hill phylogenetic diversity in your package.

**Comment by daijiang** [comment]
I think the `FD::divc()` and `ade4::divc()` used d_ij^2 and then divided 2 and sum of d_ij^2 to try to standardize Rao's Q results, so they are less dependent with the number of species. I am not sure how effective is it. But, if one will use something like null models to account for species richness, then it will be better just use the original formula $\sum \sum p_{i} d_{ij} p_{j}$.
